Menu_items:
  type: list
  default: "Affiliated Communities, comments, Even more cool communities!, vdm"
  description:
    en: "Add menu items. One item per line in this order: Text, icon, title, view.<br><br><b>Text:</b> what appears on the menu.<br><b>Icon:</b> the icon displayed next to the item. If you do not want to use an icon, use `none`<br><b>Title:</b> the text that appears when the item is hovered.<br><b>View:</b> Choose what devices the item appears on. `vdm` appears on both desktop and mobile, `vdo` appears on desktops only, `vmo` appears on mobiles only."
Submenu_items:
  type: list
  default: "Affiliated Communities, SisterGeeks.org, none, https://SisterGeeks.org, blank, A Hub of Women's Communities|Affiliated Communities, Story.Pub, none, https://story.pub, blank, A Friendly Community for Self-Publishers|Affiliated Communities, EveryAmerican.org, none, https://everyamerican.org, blank, A Hub of US Non-Profit Orgs|Affiliated Communities, EveryAmerican.com, none, https://everyamerican.com, blank, A Hub of US Political Forums|Affiliated Communities, Discourse.Pub, none, https://discourse.pub, blank, A Hub of Friendly Discourse Forums|Affiliated Communities, Discourse.Blog, none, https://discourse.blog, blank, Jen's Dev Site for a Discourse Blog Theme|Affiliated Communities, Jen.Do, none, https://jen.do, blank, Jen's Personal Project Forums|Affiliated Communities, Privy.Pub, none, https://privy.pub, blank, Private Project Forums|Affiliated Communities, nOObish.me, none, https://noobish.me, blank, Jen's Personal Blog"
  description:
    en: "Add submenu items. One item per line in this order: Parent, text, icon, URL, target, title.<br><br><b>Parent:</b> the name of the parent menu item which this submenu item show under. Use the `text` value from the list above<br><b>Text:</b> the text that shows for this submenu item.<br><b>Icon:</b> the icon for this submenu item, use `none` if no icon is needed<br><b>URL:</b> the path this menu item links to.<br>You can use relative paths as well.<br><b>Target:</b> Choose whether this item will open in a new tab or in the same tab. Use `blank` to open the link in a new tab, or use `self` to open it in the same tab.<br><b>Title:</b> the text that shows when the item is hovered.<br><b>Dividers:</b> You can also add dividers between submenu items. To add a divider user `parent, divider`"
Svg_icons:
  type: "list"
  list_type: "compact"
  default: "fa-th|fa-magic|far-keyboard|far-money-bill-alt|fa-shopping-cart|far-lightbulb|fa-columns|fa-gift|fa-book|far-chart-bar|fab-wordpress|fa-wrench|fab-leanpub"
  description:
    en: "Include FontAwesome icon classes for each icon used in the lists above."
Fixed_mode:
  default: true
  description:
    en: "Force the menu to be visible at the top of the screen regardless of scroll position - Desktop only"
Show_caret:
  default: true
  description:
    en: "Show caret icons next to menu items"
Invert_position:
  default: true
  description:
    en: "Display menu items on the opposite side of the screen"
Menu_background:
  default: "#6d5073"
  description:
    en: "Background color for the menu. <small>(hex, rgb, rgba or CSS color name)</small>"
Menu_item_color:
  default: "#fff"
  description:
    en: "Color for menu items. <small>(hex, rgb, rgba or CSS color name)</small>"
Menu-item-active-background:
  default: "#e0e0f0"
  description:
    en: "Background color for menu items when active. <small>(hex, rgb, rgba or CSS color name)</small>"
Menu-item-active-color:
  default: "#222"
  description:
    en: "Color for menu items when active. <small>(hex, rgb, rgba or CSS color name)</small>"
Submenu_background:
  default: "#e0e0f0"
  description:
    en: "Background color for submenus. <small>(hex, rgb, rgba or CSS color name)</small>"
Submenu_item_color:
  default: "#222"
  description:
    en: "Color for submenu items. <small>(hex, rgb, rgba or CSS color name)</small>"
Submenu_item_hover_background:
  default: "#ebebf7"
  description:
    en: "Background color for submenus items when hovered. <small>(hex, rgb, rgba or CSS color name)</small>"
Submenu_item_hover_color:
  default: "#222"
  description:
    en: "Color for submenus items when hovered. <small>(hex, rgb, rgba or CSS color name)</small>"
Divider_color:
  default: "#bbb"
  description:
    en: "Color for divider lines in submenus. <small>(hex, rgb, rgba or CSS color name)</small>"
